# Generated by Django 4.2.4 on 2023-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
