# Generated by Django 4.2.4 on 2023-09-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobpost_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='cretion_date',
            new_name='creation_date',
        ),
    ]
