# Generated by Django 4.2.4 on 2023-09-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_location_jobpost_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.authors'),
        ),
    ]
